name: Build and Push Docker Image

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Increment version
      run: echo "VERSION=$((1+$(curl -s https://registry.hub.docker.com/v2/repositories/dockerp2pro/charan1/tags | jq '.count')))">> $GITHUB_ENV
      
    - name: Build and push Docker image
      uses: docker/build-push-action@v2
      with:
        context: .
        push: true
        tags: dockerp2pro/charan1:${{ env.VERSION }}
        
