name: Delete Old Workflow Runs

on:
  workflow_dispatch:
    inputs:
      workflowName:
        description: 'Name of the workflow file to delete runs from (e.g., dotnet-test.yml)'
        required: true
        

jobs:
  delete-runs:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Setup GitHub CLI
      run: |
        curl -sSL https://github.com/cli/cli/releases/download/v2.2.0/gh_2.2.0_linux_amd64.tar.gz | tar xz -C /tmp
        sudo mv /tmp/gh_*/bin/gh /usr/local/bin/

    - name: Authenticate GitHub CLI
      run: echo ${{ secrets.GITHUB_TOKEN }} | gh auth login --with-token

    - name: Delete Runs
      run: |
        repo="${{ github.repository }}"
        workflow="Your_Workflow_Name_Here" # Replace this with the name of the workflow you want to delete
        page_size=50
        page_number=1
        while : ; do
          run_ids=$(gh api -X GET "/repos/$repo/actions/workflows/$workflow/runs?per_page=$page_size&page=$page_number" --jq '.workflow_runs[] | select(.id != null) | .id')
          if [[ -z "$run_ids" ]]; then
            echo "No more runs found."
            break
          fi
          for run_id in $run_ids; do
            if [[ "$run_id" =~ ^[0-9]+$ ]]; then
              echo "Deleting run id $run_id"
              error_message=$(gh run delete $run_id --repo $repo 2>&1 >/dev/null)
              if [[ $error_message == *"gh: Not Found (HTTP 404)"* ]]; then
                echo "Encountered 404 error. Skipping..."
              fi
            fi
            sleep 2  
          done
          ((page_number++))
        done
