name: Simple Test

on:
  workflow_dispatch:
    inputs:
      deploy_environment:
        description: 'Environment'
        required: true
        type: string

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Echo Input
      run: echo "Input: ${{ github.event.inputs.deploy_environment }}"
